micronaut:
  application:
    name: propostakotlin
datasources:
  default:
    url: jdbc:mysql://localhost:3306/dbproposta_kt?useTimezone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'darthluck10'
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: create-drop
